# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cedula', models.IntegerField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField()),
                ('bandera', models.ImageField(upload_to=b'')),
                ('slogan', models.CharField(max_length=200)),
                ('cantidad_votos', models.IntegerField()),
            ],
        ),
    ]
