# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votar', '0002_auto_20160311_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('is_available', models.BooleanField()),
            ],
        ),
    ]
