# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votar', '0003_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='do_vote',
            field=models.BooleanField(default=False),
        ),
    ]
