# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votar', '0004_estudiante_do_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='cantidad_votos',
            field=models.IntegerField(null=True),
        ),
    ]
