# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-12 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votar', '0006_auto_20160312_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='cantidad_votos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
